from datetime import datetime

from pydantic import BaseModel, Field


class ActionStep(BaseModel):
    """A single remediation action step."""

    step: int
    action: str
    urgency: str = Field(description="e.g., immediate, 1hr, 24hr, 1week")
    owner: str = Field(default="Security Team", description="Responsible party")


class IncidentReport(BaseModel):
    """Complete incident report generated by the Report Agent."""

    summary: str = Field(description="Executive summary (2-3 sentences)")
    threat_count: int = Field(default=0)
    critical_count: int = Field(default=0)
    high_count: int = Field(default=0)
    medium_count: int = Field(default=0)
    low_count: int = Field(default=0)
    timeline: str = Field(
        default="", description="Reconstructed attack timeline narrative"
    )
    action_plan: list[ActionStep] = Field(
        default_factory=list, description="Ordered remediation steps"
    )
    recommendations: list[str] = Field(
        default_factory=list, description="Strategic prevention recommendations"
    )
    ioc_summary: list[str] = Field(
        default_factory=list,
        description="Indicators of Compromise (IPs, hashes, domains)",
    )
    mitre_techniques: list[str] = Field(
        default_factory=list, description="All MITRE ATT&CK techniques observed"
    )
    generated_at: datetime = Field(default_factory=datetime.now)
